#!/bin/bash

DBNAME="$USER"

# TODO support LDAP authentication via prompting in lemontest for student password and passing it here via env

# clean db
if ! psql -h localhost -p 6622 -U "$USER" -d "$DBNAME" -c "drop schema public cascade" 2>&1; then
    exit 1
fi
if ! psql -h localhost -p 6622 -U "$USER" -d "$DBNAME" -c "create schema public" 2>&1; then
    exit 1
fi

exit 0
