#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "illegal number of parameters"
    exit 1
fi

DBNAME="$USER"
read -s -p "Enter your UNSW zPassword" PASS

# pg_ctl -o "-F -h localhost -p 5432" start
echo $PASS | psql -A -h localhost -p 5432 -U "$USER" -d "$DBNAME" -c "$2"
